//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMvc_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLS
    {
        public int NUMERO { get; set; }
        public string FILENAME { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime DATE_DOC { get; set; }
        public System.DateTime DATE_PAY { get; set; }
        public System.DateTime DATE_ADD { get; set; }
        public decimal AMOUNT { get; set; }
        public int CONTRAGENT_ID { get; set; }
        public int PERIOD_ID { get; set; }
        public int TYPES_ID { get; set; }
    
        public virtual CONTRAGENTS CONTRAGENTS { get; set; }
        public virtual PERIODS PERIODS { get; set; }
        public virtual TYPESOFDOC TYPESOFDOC { get; set; }
    }
}
